/**
 * Static map from manifest path → bundled asset.
 *
 * GENERATED by scripts/gen-placeholder-audio.mjs — do not edit by hand.
 *
 * This file exists purely because Metro resolves `require()` at build time and
 * cannot take a dynamic string, so a manifest full of paths can't be turned
 * into bundled assets without listing them literally.
 *
 * It is *temporary scaffolding for local placeholders only*. Once audio is
 * served from R2, `resolveAudioSource` in source.ts returns a `{ uri }` and
 * this whole file is deleted — nothing else imports it.
 */

import type { AudioAsset } from './source';

export const LOCAL_AUDIO: Record<string, AudioAsset> = {
  'kho-ngu/breathing/tho-01.m4a': require('../assets/audio/kho-ngu/breathing/tho-01.m4a'),
  'kho-ngu/breathing/tho-02.m4a': require('../assets/audio/kho-ngu/breathing/tho-02.m4a'),
  'kho-ngu/breathing/tho-03.m4a': require('../assets/audio/kho-ngu/breathing/tho-03.m4a'),
  'kho-ngu/breathing/tho-04.m4a': require('../assets/audio/kho-ngu/breathing/tho-04.m4a'),
  'kho-ngu/breathing/tho-05.m4a': require('../assets/audio/kho-ngu/breathing/tho-05.m4a'),
  'kho-ngu/meditation/thien-01.m4a': require('../assets/audio/kho-ngu/meditation/thien-01.m4a'),
  'kho-ngu/meditation/thien-02.m4a': require('../assets/audio/kho-ngu/meditation/thien-02.m4a'),
  'kho-ngu/meditation/thien-03.m4a': require('../assets/audio/kho-ngu/meditation/thien-03.m4a'),
  'kho-ngu/meditation/thien-04.m4a': require('../assets/audio/kho-ngu/meditation/thien-04.m4a'),
  'kho-ngu/meditation/thien-05.m4a': require('../assets/audio/kho-ngu/meditation/thien-05.m4a'),
  'kho-ngu/story/truyen-01.m4a': require('../assets/audio/kho-ngu/story/truyen-01.m4a'),
  'kho-ngu/story/truyen-02.m4a': require('../assets/audio/kho-ngu/story/truyen-02.m4a'),
  'kho-ngu/story/truyen-03.m4a': require('../assets/audio/kho-ngu/story/truyen-03.m4a'),
  'kho-ngu/story/truyen-04.m4a': require('../assets/audio/kho-ngu/story/truyen-04.m4a'),
  'kho-ngu/story/truyen-05.m4a': require('../assets/audio/kho-ngu/story/truyen-05.m4a'),

  'stress/breathing/tho-01.m4a': require('../assets/audio/stress/breathing/tho-01.m4a'),
  'stress/breathing/tho-02.m4a': require('../assets/audio/stress/breathing/tho-02.m4a'),
  'stress/breathing/tho-03.m4a': require('../assets/audio/stress/breathing/tho-03.m4a'),
  'stress/breathing/tho-04.m4a': require('../assets/audio/stress/breathing/tho-04.m4a'),
  'stress/breathing/tho-05.m4a': require('../assets/audio/stress/breathing/tho-05.m4a'),
  'stress/meditation/thien-01.m4a': require('../assets/audio/stress/meditation/thien-01.m4a'),
  'stress/meditation/thien-02.m4a': require('../assets/audio/stress/meditation/thien-02.m4a'),
  'stress/meditation/thien-03.m4a': require('../assets/audio/stress/meditation/thien-03.m4a'),
  'stress/meditation/thien-04.m4a': require('../assets/audio/stress/meditation/thien-04.m4a'),
  'stress/meditation/thien-05.m4a': require('../assets/audio/stress/meditation/thien-05.m4a'),
  'stress/story/truyen-01.m4a': require('../assets/audio/stress/story/truyen-01.m4a'),
  'stress/story/truyen-02.m4a': require('../assets/audio/stress/story/truyen-02.m4a'),
  'stress/story/truyen-03.m4a': require('../assets/audio/stress/story/truyen-03.m4a'),
  'stress/story/truyen-04.m4a': require('../assets/audio/stress/story/truyen-04.m4a'),
  'stress/story/truyen-05.m4a': require('../assets/audio/stress/story/truyen-05.m4a'),

  'that-tinh/breathing/tho-01.m4a': require('../assets/audio/that-tinh/breathing/tho-01.m4a'),
  'that-tinh/breathing/tho-02.m4a': require('../assets/audio/that-tinh/breathing/tho-02.m4a'),
  'that-tinh/breathing/tho-03.m4a': require('../assets/audio/that-tinh/breathing/tho-03.m4a'),
  'that-tinh/breathing/tho-04.m4a': require('../assets/audio/that-tinh/breathing/tho-04.m4a'),
  'that-tinh/breathing/tho-05.m4a': require('../assets/audio/that-tinh/breathing/tho-05.m4a'),
  'that-tinh/meditation/thien-01.m4a': require('../assets/audio/that-tinh/meditation/thien-01.m4a'),
  'that-tinh/meditation/thien-02.m4a': require('../assets/audio/that-tinh/meditation/thien-02.m4a'),
  'that-tinh/meditation/thien-03.m4a': require('../assets/audio/that-tinh/meditation/thien-03.m4a'),
  'that-tinh/meditation/thien-04.m4a': require('../assets/audio/that-tinh/meditation/thien-04.m4a'),
  'that-tinh/meditation/thien-05.m4a': require('../assets/audio/that-tinh/meditation/thien-05.m4a'),
  'that-tinh/story/truyen-01.m4a': require('../assets/audio/that-tinh/story/truyen-01.m4a'),
  'that-tinh/story/truyen-02.m4a': require('../assets/audio/that-tinh/story/truyen-02.m4a'),
  'that-tinh/story/truyen-03.m4a': require('../assets/audio/that-tinh/story/truyen-03.m4a'),
  'that-tinh/story/truyen-04.m4a': require('../assets/audio/that-tinh/story/truyen-04.m4a'),
  'that-tinh/story/truyen-05.m4a': require('../assets/audio/that-tinh/story/truyen-05.m4a'),

  'khoi-dau/breathing/tho-01.m4a': require('../assets/audio/khoi-dau/breathing/tho-01.m4a'),
  'khoi-dau/breathing/tho-02.m4a': require('../assets/audio/khoi-dau/breathing/tho-02.m4a'),
  'khoi-dau/breathing/tho-03.m4a': require('../assets/audio/khoi-dau/breathing/tho-03.m4a'),
  'khoi-dau/breathing/tho-04.m4a': require('../assets/audio/khoi-dau/breathing/tho-04.m4a'),
  'khoi-dau/breathing/tho-05.m4a': require('../assets/audio/khoi-dau/breathing/tho-05.m4a'),
  'khoi-dau/meditation/thien-01.m4a': require('../assets/audio/khoi-dau/meditation/thien-01.m4a'),
  'khoi-dau/meditation/thien-02.m4a': require('../assets/audio/khoi-dau/meditation/thien-02.m4a'),
  'khoi-dau/meditation/thien-03.m4a': require('../assets/audio/khoi-dau/meditation/thien-03.m4a'),
  'khoi-dau/meditation/thien-04.m4a': require('../assets/audio/khoi-dau/meditation/thien-04.m4a'),
  'khoi-dau/meditation/thien-05.m4a': require('../assets/audio/khoi-dau/meditation/thien-05.m4a'),

  'hang-ngay/breathing/tho-01.m4a': require('../assets/audio/hang-ngay/breathing/tho-01.m4a'),
  'hang-ngay/breathing/tho-02.m4a': require('../assets/audio/hang-ngay/breathing/tho-02.m4a'),
  'hang-ngay/breathing/tho-03.m4a': require('../assets/audio/hang-ngay/breathing/tho-03.m4a'),
  'hang-ngay/breathing/tho-04.m4a': require('../assets/audio/hang-ngay/breathing/tho-04.m4a'),
  'hang-ngay/breathing/tho-05.m4a': require('../assets/audio/hang-ngay/breathing/tho-05.m4a'),
  'hang-ngay/meditation/thien-01.m4a': require('../assets/audio/hang-ngay/meditation/thien-01.m4a'),
  'hang-ngay/meditation/thien-02.m4a': require('../assets/audio/hang-ngay/meditation/thien-02.m4a'),
  'hang-ngay/meditation/thien-03.m4a': require('../assets/audio/hang-ngay/meditation/thien-03.m4a'),
  'hang-ngay/meditation/thien-04.m4a': require('../assets/audio/hang-ngay/meditation/thien-04.m4a'),
  'hang-ngay/meditation/thien-05.m4a': require('../assets/audio/hang-ngay/meditation/thien-05.m4a'),
  'hang-ngay/story/truyen-01.m4a': require('../assets/audio/hang-ngay/story/truyen-01.m4a'),
  'hang-ngay/story/truyen-02.m4a': require('../assets/audio/hang-ngay/story/truyen-02.m4a'),
  'hang-ngay/story/truyen-03.m4a': require('../assets/audio/hang-ngay/story/truyen-03.m4a'),
  'hang-ngay/story/truyen-04.m4a': require('../assets/audio/hang-ngay/story/truyen-04.m4a'),
  'hang-ngay/story/truyen-05.m4a': require('../assets/audio/hang-ngay/story/truyen-05.m4a'),
};
